#      _   ____        __          __            _
#     / | / / /_______/ /   ____  / /____  _____(_)___ _
#    /  |/ / //_/ ___/ /   / __ \/ __/ _ \/ ___/ / __ `/
#   / /|  / ,< (__  ) /___/ /_/ / /_/  __/ /  / / /_/ /
#  /_/ |_/_/|_/____/_____/\____/\__/\___/_/  /_/\__,_/

# Configurações relacionadas ao dinheiro do jogador.
saque:
  # Define se quando o jogador efetuar uma aposta, deverá tirar dinheiro dele.
  habilitar: true

  # Define a quantidade de money retirada do jogador após uma aposta, se ativo.
  # - É importante usar a formatação como: '1K', '10B' ..., tendo como
  # base três números e letras como máximo: '100B', '999SS' ...
  valor: '10K'

# Define os prêmios
# - Caso não queria algum valor já pré definido, basta remover o valor,
# mas fique ciente que quando dado um prêmio que aqui foi removido, isso não vai funcionar.
deposito:

  # Lista de valores dos prêmios quando o jogador acertar o número do sorteio.
  # - É necessário seguir o padrão corretamente, por outro lado, o sistema de deposito
  # pode não funcionar corretamente.
  premios:
    - "K,1E3"
    - "M,1E6",
    - "B,1E9",
    - "T,1E12",
    - "Q,1E15",
    - "QQ,1E18",
    - "S,1E21",
    - "SS,1E24",
    - "OC,1E27",
    - "N,1E30",
    - "D,1E33",
    - "UN,1E36",
    - "DD,1E39",
    - "TR,1E42",
    - "QT,1E45",
    - "QN,1E48",
    - "SD,1E51",
    - "SPD,1E54",
    - "OD,1E57",
    - "ND,1E60",
    - "VG,1E63",
    - "UVG,1E66",
    - "DVG,1E69",
    - "TVG,1E72",
    - "QTV,1E75",
    - "QNV,1E78",
    - "SEV,1E81",
    - "SPV,1E84",
    - "OVG,1E87",
    - "NVG,1E90",
    - "TG,1E93"

# Define mensagens geral do evento.
mensagens:

  # Define se todas as mensagens do evento devem aparecer.
  habilitar: true


  # Define a mensagem quando o evento começa.
  inicio:
    - ''
    - 'EVENTO LOTERIA COMEÇOU'
    - ''
    - '| Evento loteria ativo'
    - '| Basta usar /loteria (número) para apostar'
    - '| Prêmio estimado [{premio_estimado}]'
    - ''

  # Define a mensagem quando o há um vencedor.
  acerto:
    - ''
    - '&b&l| &2EVENTO LOTERIA!'
    - '&b&l| Que sorte o &6{apostador} &facertou o número da sorte!'
    - '&b&l| O mesmo recebeu o valor de {premio_quantidade}'
    - ''
    - 'Evento encerrado'
    - ''

  # Define a mensagem quando possui evento ativo, somente admins.
  sorteio:
    - ''
    - '| §eSorteio ativo'
    - '| Número da loteria: [{numero_loteria}]'
    - ''

  nenhum-sorteio-ativo: 'Não possui nenhum sorteio ativo no momento'

  admin:

    sorteio-encerrar: 'Você acabou de finalizar um sorteio'
    numero-sorteado: 'Um número já foi sorteado, espere até encerrar ou finalizar /loteria encerrar'

  jogador:

    erro-na-aposta: 'Você pode apostar apenas número'
    tentativa: 'Que pena, você errou!'

  sem-permissao: 'Você não tem permissão para executar esse comando'
  sem-ganhador: 'Evento encerrado, não houve ganhador'

config:

  # Define por quanto tempo a loteria vai ficar ativa enquanto não houve ganhador.
  # - Caso houver ganhador a loteria vai encerrar automaticamente.
  tempo-loteria: 100

  # Define a tag quando alguma ação não mapeada ocorrer exemplo:
  # NiksLoteria ➡ Não há sorteio ativo no momento
  # - Tag visível somente para admins.
  plugin-tag: '&a&lNksLoteria &8➡'


