name: NksLoteria
version: '${version}'
main: com.nicolas.nkloteria.Main
api-version: '1.8'
depend: ["Vault"]
softdepend: ["NextEconomy", "SolaryEconomy"]
load: STARTUP

commands:
  loteria:
    description: iniciar o sorteio da loteria
    aliases:
      - lt
      - lta
      - ltra
